DDPM_config:
  n_steps: 1000
  schedule: 'linear' 
  min_beta: 0.0001
  max_beta: 0.02
  vector_c: 4
  vector_l: 618

DIT_config_film:
  seq_len : 618
  seq_channels : 8
  patch_size : 1
  channels_out: 4
  num_layers : 12
  hidden_size : 512
  num_heads : 8
  head_dim : 64
  timestep_emb_dim : 512
  class_emb_dim: 128
  context_dim: 4950
  age_dim: 126

DIT_config_cat:
  seq_len : 618
  seq_channels : 8
